<?php

namespace Tests\Browser\Concerns;

/**
 * Inline the stylesheets a rendered page ACTUALLY LINKS, so a `file://` capture looks like the page.
 *
 * **Found by prompt 206, and it had been quietly wrong.** Both counter harnesses inlined
 * `glob(public_path('build/assets/*.css'))` — every stylesheet in the build, concatenated. That pulls in
 * Filament's `theme-*.css`, which a counter screen never loads, and which ends with its own copy of the
 * Tailwind utility layer. Its `.hidden{display:none}` therefore landed AFTER app.css's
 * `@media (width>=64rem){.lg\:inline{display:inline}}` — equal specificity, later wins — so every
 * `hidden lg:inline` label in the top bar was forced off **at every width**.
 *
 * What that cost: `measure-topbar.mjs` has been measuring an icon-only row and reporting PASS, when the row
 * a 1180px tablet really renders is the labelled one — the wider of the two, and the only one that could
 * overlap. Same defect class as the two 205 recorded about this script: an instrument that reports on
 * something other than the thing.
 *
 * Inlining exactly the `<link>`s the page emitted is faithful by construction, and stays faithful if the
 * build splits or renames a chunk.
 *
 * **Prompt 233 — and the fonts have to resolve too.** The inlined CSS carries `url(/build/assets/inter-*.woff2)`,
 * a ROOT-relative path. On the `file://` pages these snapshots are, that resolves against the filesystem root,
 * every face fails, and the browser silently falls back to whatever the runner's OS has. Measured: on the
 * snapshot `document.fonts.check('16px Inter')` was **false** with the latin face in `error`, and a probe
 * string measured **322px** against **339px** on the live page — 5% narrower. Every text-driven number these
 * harnesses assert (row heights, content heights, headroom) was the fallback font's, not the app's: the same
 * commit measured green on a Mac (Helvetica-ish fallback) and red on Linux (DejaVu-ish, taller).
 *
 * So the build's own URLs are rewritten to absolute `file://` paths into `public/build`. The snapshot then
 * loads the very woff2 the app serves — not a copy, not an approximation. Chosen over inlining the subsets as
 * `data:` URLs because it is exact, adds nothing to the file, and cannot drift from the build.
 */
trait InlinesBuiltCss
{
    protected function inlineBuiltCss(string $html): string
    {
        $html = (string) preg_replace_callback(
            '#<link[^>]*href="[^"]*/build/(assets/[^"]+\.css)"[^>]*>#',
            function (array $match): string {
                $path = public_path('build/'.$match[1]);

                return is_file($path) ? '<style>'.$this->resolvableAssetUrls((string) file_get_contents($path)).'</style>' : '';
            },
            $html,
        );

        return $html;
    }

    /**
     * Point the stylesheet's root-relative asset URLs at the real files (prompt 233).
     *
     * A `file://` page has no document root, so `url(/build/assets/inter-…woff2)` never resolves and the text
     * is measured in a fallback font. These snapshots are regenerated by their harness test on every run, so
     * an absolute local path in one is not a portability problem — it is what makes the capture faithful.
     */
    private function resolvableAssetUrls(string $css): string
    {
        $root = 'file://'.public_path('build/');

        return (string) preg_replace('#url\((["\']?)/build/#', 'url($1'.$root, $css);
    }
}
